### ISSUE TITLE
KVH already available drivers

### ISSUE THREAD

**Issue by traversaro** [robotology-playground/kvh-yarp-devices#1]
There are two ROS driver available for KVH 1750 : 
* https://github.com/TRECVT/ros_kvh1750
* https://github.com/RIVeR-Lab/kvh (this also supports CG-5100)

There is a ROS python driver available for an unspecified KVH gyroscope:
* https://github.com/oceansystemslab/kvh_gyroscope

There is a ROS driver for the KVH DSP 3000: 
* https://github.com/ros-drivers/kvh_drivers

There is also one orogen driver, again for the KVH 1750 : 
* https://github.com/Brazilian-Institute-of-Robotics/drivers-orogen-imu_kvh_1750

My current plan is to check if the code of the first driver (https://github.com/TRECVT/ros_kvh1750) can work also with the KVH 1775, and port the C++ part to a Catkin-free independent library (properly referencing the original driver), and then use that library in the actual YARP device.

**Comment by iron76** [comment]
👍

**Comment by traversaro** [comment]
The message of KVH 1750 are bit by bit compatible by the default message of KVH 1775, so the driver should be compatible. 
The code needs to be modified if we want to read magnetometers raw data, that uses another type of message of the KVH 1775 .

**Comment by traversaro** [comment]
Ref: 
 KVH 1750 Manual : www.kvh.com/ViewAttachment.aspx?guidID=%7BD9E4BCAC-F4B3-4947-BC6E-F276497CBCAA%7D 
 KVH 1775 Manual : www.kvh.com/ViewAttachment.aspx?guidID=%7B009C3B90-57A8-4AFA-9DAB-F79F2F2B41C6%7D

**Comment by traversaro** [comment]
First version compiling committed in https://github.com/robotology-playground/kvh-yarp-devices/commit/0d3f8c0279b454929a8253cfa6603b0698b430d4 . This version just reads angular velocity and acceleration, and is not configurable from configuration file. Still needs to be tested.

**Comment by traversaro** [comment]
We imported the C++ library from https://github.com/TRECVT/ros_kvh1750 , and use that one in a pure CMake proejct with an additional YARP Driver.
