### ISSUE TITLE
Errors when checking the plugin installation

### ISSUE THREAD

**Issue by gabrielenava** [robotology-playground/kvh-yarp-devices#4]
Following the instructions of this page, I was trying to check if the plugin has been correctly installed by running the command:

`yarp plugin kvh17xx`

I got the following error, despite the plugin should be installed correctly, and the path in my `.bashrc` is pointing the installation/share folder:

```
Yes, this is a YARP plugin
error while opening /home/gnava/Software/codyco-superbuild/build/install/lib/yarp/kvh17xx.so:
/home/gnava/Software/codyco-superbuild/build/install/lib/yarp/kvh17xx.so: undefined symbol: kvh17xx
Cannot find or load shared library

```

**Comment by traversaro** [comment]
The CMake had the `ENABLE_kvh17xx` set to `OFF`, and this was causing this missing symbol. @gabrielenava is in charge of migrating the CMake to make sure that everything necessary is always compiled.

**Comment by traversaro** [comment]
@gabrielenava did you fixed this?

**Comment by gabrielenava** [comment]
should have been fixed with this PR: https://github.com/robotology-playground/kvh-yarp-devices/pull/5
